name: Build and Package Number System Converter GUI

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev qtchooser
          sudo apt-get install -y linuxdeployqt

      - name: Create Build Folder
        run: mkdir build && cd build

      - name: Build Project with qmake and make
        run: |
          cd build
          qmake ..
          make -j$(nproc)  # Adjust parallel jobs based on the number of CPU cores

      - name: Package Linux App with linuxdeployqt
        run: |
          cd build
          linuxdeployqt "Number System Converter GUI" -appimage

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Linux-AppImage
          path: build/Number\ System\ Converter\ GUI*.AppImage

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Install Qt for Windows
        run: |
          choco install qt

      - name: Create Build Folder
        run: mkdir build && cd build

      - name: Build Project with qmake and nmake
        run: |
          cd build
          qmake ..
          nmake

      - name: Package Windows App with windeployqt
        run: |
          cd build
          "C:\Qt\Tools\QtCreator\bin\windeployqt.exe" "Number System Converter GUI.exe"

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Windows-Executable
          path: build/"Number System Converter GUI.exe"

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Install Qt for macOS
        run: |
          brew install qt

      - name: Create Build Folder
        run: mkdir build && cd build

      - name: Build Project with qmake and make
        run: |
          cd build
          qmake ..
          make -j$(sysctl -n hw.ncpu)  # Automatically use all CPU cores

      - name: Package macOS App
        run: |
          cd build
          macdeployqt "Number System Converter GUI.app"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: macOS-App
          path: build/"Number System Converter GUI.app"

  upload-release:
    name: Upload All Artifacts to Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Create GitHub Release
        id: create_release
        uses: gh actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release for version ${{ github.ref }}"

      - name: Upload Linux Artifact to GitHub Release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/Number\ System\ Converter\ GUI*.AppImage
          asset_name: "Number System Converter GUI-linux-${{ github.ref }}.AppImage"
          asset_content_type: application/vnd.appimage

      - name: Upload Windows Artifact to GitHub Release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/"Number System Converter GUI.exe"
          asset_name: "Number System Converter GUI-windows-${{ github.ref }}.exe"
          asset_content_type: application/octet-stream

      - name: Upload macOS Artifact to GitHub Release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/"Number System Converter GUI.app"
          asset_name: "Number System Converter GUI-macos-${{ github.ref }}.app"
          asset_content_type: application/octet-stream
